# Generated by Django 5.1.7 on 2025-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_banco', models.CharField(max_length=10)),
                ('cnpj_curto', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('nome_curto', models.CharField(max_length=100)),
                ('nome_longo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sis_bancos',
                'ordering': ['num_banco'],
            },
        ),
    ]
