# Generated by Django 5.1.7 on 2025-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='cnpj',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='cnpj_curto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='nome_curto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='nome_longo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='num_banco',
            field=models.CharField(max_length=20),
        ),
    ]
