# Generated by Django 5.1.7 on 2025-03-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0002_alter_bancos_cnpj_alter_bancos_cnpj_curto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='num_banco',
            field=models.CharField(max_length=200),
        ),
    ]
