# Generated by Django 5.1.7 on 2025-03-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0003_alter_bancos_num_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='cnpj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='cnpj_curto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='nome_curto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='nome_longo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='num_banco',
            field=models.TextField(),
        ),
    ]
