# Generated by Django 5.1.7 on 2025-03-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0004_alter_bancos_cnpj_alter_bancos_cnpj_curto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancos',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='bancos',
            name='data_ultima_edicao',
        ),
    ]
