# Generated by Django 5.1.7 on 2025-03-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0005_remove_bancos_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancos',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='bancos',
            name='cnpj_curto',
        ),
        migrations.RemoveField(
            model_name='bancos',
            name='nome_curto',
        ),
        migrations.RemoveField(
            model_name='bancos',
            name='nome_longo',
        ),
        migrations.AddField(
            model_name='bancos',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='num_banco',
            field=models.IntegerField(),
        ),
    ]
