# Generated by Django 5.1.7 on 2025-03-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0006_remove_bancos_cnpj_remove_bancos_cnpj_curto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='nome',
            field=models.TextField(null=True),
        ),
    ]
