# Generated by Django 5.1.7 on 2025-04-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_bancos', '0007_alter_bancos_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancos',
            options={'ordering': ['nome']},
        ),
    ]
