# Generated by Django 5.1.7 on 2025-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marcas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={'ordering': ['sigla']},
        ),
        migrations.AddField(
            model_name='marcas',
            name='sigla',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
