# Generated by Django 5.1.7 on 2025-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_marcas', '0002_alter_marcas_options_marcas_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='sigla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
