# Generated by Django 5.1.7 on 2025-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_regioes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
