# Generated by Django 5.1.7 on 2025-03-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emitentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código da Loja')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Loja')),
                ('status', models.BooleanField(default=True, verbose_name='Status do Emitente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Data da Ultima Edição')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_cidades.cidades', verbose_name='Cidade da Loja')),
            ],
            options={
                'db_table': 'sis_emitentes',
                'ordering': ['nome'],
            },
        ),
    ]
