# Generated by Django 5.1.7 on 2025-03-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_configuracoes_veiculo', '0004_alter_configuracoesveiculo_options_and_more'),
        ('crm_modelos', '0002_modelos_sigla_alter_modelos_familia_produto'),
        ('sis_emitentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('nf_compra', models.IntegerField(blank=True, null=True)),
                ('nf_venda', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('configuracao_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_configuracoes_veiculo.configuracoesveiculo')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_emitentes.emitentes')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_modelos.modelos')),
            ],
            options={
                'db_table': 'crm_veiculos',
                'ordering': ['modelo'],
            },
        ),
    ]
