# Generated by Django 5.1.7 on 2025-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='data_quitação',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='prazo_free',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
