# Generated by Django 5.1.7 on 2025-03-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_veiculos', '0002_veiculos_data_compra_veiculos_data_quitação_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculos',
            old_name='data_quitação',
            new_name='data_quitacao',
        ),
    ]
