# Generated by Django 5.1.7 on 2025-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_veiculos', '0003_rename_data_quitação_veiculos_data_quitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='chassi',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
