# Generated by Django 5.1.7 on 2025-03-31 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_acessorios_veiculo', '0002_alter_acessoriosveiculo_descricao'),
        ('crm_veiculos', '0004_alter_veiculos_chassi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='configuracao_veiculo',
        ),
        migrations.AddField(
            model_name='veiculos',
            name='acessorio_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_acessorios_veiculo.acessoriosveiculo'),
        ),
    ]
