# Generated by Django 5.1.7 on 2025-03-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_acessorios_veiculo', '0001_initial'),
        ('crm_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_acessorios_veiculo.acessoriosveiculo', verbose_name='Acessorio da Configuração')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_produtos.produtos', verbose_name='Produto da Configuração')),
            ],
            options={
                'db_table': 'crm_configuracoes_veiculo',
                'ordering': ['produto'],
            },
        ),
    ]
