# Generated by Django 5.1.7 on 2025-03-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_configuracoes_veiculo', '0002_alter_configuracoesveiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoesveiculo',
            options={'ordering': ['descricao']},
        ),
        migrations.AddField(
            model_name='configuracoesveiculo',
            name='descricao',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome da Configuração'),
        ),
    ]
