# Generated by Django 5.1.7 on 2025-03-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_configuracoes_veiculo', '0003_alter_configuracoesveiculo_options_and_more'),
        ('crm_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoesveiculo',
            options={'ordering': ['produto']},
        ),
        migrations.RemoveField(
            model_name='configuracoesveiculo',
            name='modelo',
        ),
        migrations.AddField(
            model_name='configuracoesveiculo',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm_produtos.produtos', verbose_name='Produto da Configuração'),
        ),
        migrations.AlterField(
            model_name='configuracoesveiculo',
            name='descricao',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição da Configuração'),
        ),
    ]
