# Generated by Django 5.1.7 on 2025-03-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_configuracoes_veiculo', '0004_alter_configuracoesveiculo_options_and_more'),
        ('crm_modelos', '0002_modelos_sigla_alter_modelos_familia_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracoesveiculo',
            options={'ordering': ['modelo']},
        ),
        migrations.RemoveField(
            model_name='configuracoesveiculo',
            name='produto',
        ),
        migrations.AddField(
            model_name='configuracoesveiculo',
            name='modelo',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_modelos.modelos', verbose_name='Produto da Configuração'),
        ),
    ]
