# Generated by Django 5.1.7 on 2025-03-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_emitentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Vendedor')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome do Vendedor')),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Vendedor')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular do Vendedor')),
                ('usuario_crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Usuário CRM do Vendedor')),
                ('senha_crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Senha CRM do Vendedor')),
                ('status', models.BooleanField(default=True, verbose_name='Status do Vendedor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_emitentes.emitentes', verbose_name='Emitente do Vendedor')),
            ],
            options={
                'db_table': 'crm_vendedores',
                'ordering': ['nome'],
            },
        ),
    ]
