# Generated by Django 5.1.7 on 2025-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('incidencia', models.CharField(max_length=20)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=True, verbose_name='Status do Emitente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sis_impostos',
                'ordering': ['descricao'],
            },
        ),
    ]
