# Generated by Django 5.1.7 on 2025-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=50)),
                ('populacao', models.IntegerField(default=0)),
                ('porte', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sis_cidades',
                'ordering': ['municipio'],
            },
        ),
    ]
