# Generated by Django 5.1.7 on 2025-03-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoOS',
            fields=[
                ('atd_id_atendimento', models.IntegerField(db_column='ATD_IdAtendimento', primary_key=True, serialize=False)),
                ('emp_cod_filial', models.CharField(blank=True, db_column='EMP_CodFilial', max_length=20, null=True)),
                ('emp_cnpj', models.CharField(blank=True, db_column='EMP_CNPJ', max_length=14, null=True)),
                ('emp_nome', models.CharField(blank=True, db_column='EMP_Nome', max_length=200, null=True)),
                ('emp_cidade', models.CharField(blank=True, db_column='EMP_Cidade', max_length=600, null=True)),
                ('emp_uf', models.CharField(blank=True, db_column='EMP_UF', max_length=2, null=True)),
                ('os_id_os', models.IntegerField(db_column='OS_IdOS')),
                ('os_fstatus', models.IntegerField(blank=True, db_column='OS_FStatus', null=True)),
                ('os_id_cliente', models.IntegerField(blank=True, db_column='OS_IdCliente', null=True)),
                ('cli_codigo_cliente', models.CharField(blank=True, db_column='CLI_CodigoCliente', max_length=20, null=True)),
                ('cli_nome', models.CharField(blank=True, db_column='CLI_Nome', max_length=600, null=True)),
                ('cli_cnpj_cpf', models.CharField(blank=True, db_column='CLI_CNPJ_CPF', max_length=20, null=True)),
                ('usr_cod_usuario', models.CharField(blank=True, db_column='USR_CodUsuario', max_length=50, null=True)),
                ('usr_nome_usuario', models.CharField(blank=True, db_column='USR_NomeUsuario', max_length=200, null=True)),
                ('atd_dsc_causa', models.TextField(blank=True, db_column='ATD_DscCausa', null=True)),
                ('atd_part_number_causadora', models.TextField(blank=True, db_column='ATD_partNumberCausadora', null=True)),
                ('atd_dsc_solucao', models.TextField(blank=True, db_column='ATD_DscSolucao', null=True)),
                ('atd_contado_cliente', models.CharField(blank=True, db_column='ATD_ContadoCliente', max_length=100, null=True)),
                ('atd_contato_telefone', models.CharField(blank=True, db_column='ATD_ContatoTelefone', max_length=20, null=True)),
                ('atd_dth_registro', models.DateTimeField(blank=True, db_column='ATD_DthRegistro', null=True)),
                ('atd_fstatus', models.IntegerField(blank=True, db_column='ATD_FStatus', null=True)),
                ('atd_ano', models.IntegerField(blank=True, db_column='ATD_Ano', null=True)),
                ('atd_mes', models.IntegerField(blank=True, db_column='ATD_Mes', null=True)),
                ('atd_horimetro', models.IntegerField(blank=True, db_column='ATD_Horimetro', null=True)),
                ('atd_dsc_opcional', models.TextField(blank=True, db_column='ATD_DscOpcional', null=True)),
                ('atd_duracao_atendimento', models.FloatField(blank=True, db_column='ATD_DuracaoAtendimento', null=True)),
                ('atd_dth_primeiro_ocorrencia', models.DateTimeField(blank=True, db_column='ATD_DthPrimeiroOcorrencia', null=True)),
                ('atd_dth_ultima_ocorrencia', models.DateTimeField(blank=True, db_column='ATD_DthUltimaOcorrencia', null=True)),
                ('dth_registro', models.DateTimeField(blank=True, db_column='dthRegistro', null=True)),
                ('os_nr_os', models.ForeignKey(db_column='OS_NrOS', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico_atendimento', to='ordens_servico.ordemservico')),
            ],
            options={
                'db_table': 'cd_matra_atendimentos_os',
                'ordering': ['atd_dth_primeiro_ocorrencia'],
            },
        ),
    ]
