# Generated by Django 5.1.7 on 2025-03-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_clientes', '0002_clientes_emitente'),
        ('crm_veiculos', '0001_initial'),
        ('crm_vendedores', '0001_initial'),
        ('sis_emitentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_clientes.clientes')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_emitentes.emitentes')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_veiculos.veiculos')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_vendedores.vendedores')),
            ],
            options={
                'db_table': 'crm_pedidos_venda',
                'ordering': ['cliente'],
            },
        ),
    ]
