# Generated by Django 5.1.7 on 2025-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosvenda',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='status_negociacao',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
