# Generated by Django 5.1.7 on 2025-03-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0002_pedidosvenda_observacoes_and_more'),
        ('sis_bancos', '0007_alter_bancos_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosvenda',
            old_name='valor',
            new_name='valor_entrada',
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='banco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sis_bancos.bancos'),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='linha_credito',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='porcent_financiamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='taxa_flat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidosvenda',
            name='status_negociacao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
