# Generated by Django 5.1.7 on 2025-03-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0003_rename_valor_pedidosvenda_valor_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosvenda',
            name='taxa_flat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
