# Generated by Django 5.1.7 on 2025-03-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0005_alter_pedidosvenda_veiculo'),
        ('crm_veiculos', '0004_alter_veiculos_chassi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosvenda',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_veiculos.veiculos'),
        ),
    ]
