# Generated by Django 5.1.7 on 2025-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0006_alter_pedidosvenda_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosvenda',
            name='valor_entrada',
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='data_envio_proposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='outras_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='outras_receitas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidosvenda',
            name='situacao_financiamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosvenda',
            name='porcent_financiamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
