# Generated by Django 5.1.7 on 2025-04-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0007_remove_pedidosvenda_valor_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosvenda',
            old_name='valor_total',
            new_name='valor',
        ),
    ]
