# Generated by Django 5.1.7 on 2025-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0008_rename_valor_total_pedidosvenda_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosvenda',
            name='status_financiamento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
