# Generated by Django 5.1.7 on 2025-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pedidos_venda', '0009_pedidosvenda_status_financiamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosvenda',
            name='data_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
