# Generated by Django 5.1.7 on 2025-03-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Cliente')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome do Cliente')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ do Cliente')),
                ('tipo_cliente', models.CharField(max_length=20, verbose_name='Tipo do Cliente')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_cidades.cidades', verbose_name='Cidade do Cliente')),
            ],
            options={
                'db_table': 'crm_clientes',
                'ordering': ['nome'],
            },
        ),
    ]
