# Generated by Django 5.1.7 on 2025-03-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0001_initial'),
        ('sis_emitentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='emitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_emitentes.emitentes', verbose_name='Cidade do Cliente'),
        ),
    ]
