# Generated by Django 5.1.7 on 2025-04-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0002_clientes_emitente'),
        ('crm_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='clientes',
            name='categoria',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='e_mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='frota_ativa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='frota_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='status_relacionamento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm_vendedores.vendedores', verbose_name='Vendedor do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Cliente'),
        ),
    ]
