# Generated by Django 5.1.7 on 2025-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0003_remove_clientes_sobrenome_clientes_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='area_plantada',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='indicador_temperatura',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
