# Generated by Django 5.1.7 on 2025-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0004_clientes_area_plantada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='area_plantada',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
