# Generated by Django 5.1.7 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0005_alter_clientes_area_plantada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf_cnpj',
            field=models.CharField(max_length=50, verbose_name='CPF/CNPJ do Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
