# Generated by Django 5.1.7 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0006_alter_clientes_cpf_cnpj_alter_clientes_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
