# Generated by Django 5.1.7 on 2025-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_clientes', '0007_alter_clientes_latitude_alter_clientes_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
