# Generated by Django 5.1.7 on 2025-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('os_nr_os', models.CharField(db_column='OS_NrOS', max_length=20, primary_key=True, serialize=False)),
                ('emp_cod_filial', models.CharField(db_column='EMP_CodFilial', max_length=20)),
                ('emp_cnpj', models.CharField(db_column='EMP_CNPJ', max_length=14)),
                ('emp_nome', models.CharField(db_column='EMP_Nome', max_length=210)),
                ('emp_cidade', models.CharField(db_column='EMP_Cidade', max_length=600)),
                ('emp_uf', models.CharField(db_column='EMP_UF', max_length=2)),
                ('os_id_os', models.IntegerField(db_column='OS_IdOS')),
                ('os_id_cliente', models.IntegerField(db_column='OS_IdCliente')),
                ('os_id_equipamento', models.IntegerField(blank=True, db_column='OS_IdEquipamento', null=True)),
                ('os_dt_avaria', models.DateTimeField(blank=True, db_column='OS_dtAvaria', null=True)),
                ('os_id_situacao_os', models.IntegerField(blank=True, db_column='OS_IdSituacaoOS', null=True)),
                ('sit_cod_situacao_os', models.CharField(blank=True, db_column='SIT_CodSituacaoOS', max_length=20, null=True)),
                ('sit_dsc_situacao_os', models.CharField(blank=True, db_column='SIT_DscSituacaoOS', max_length=100, null=True)),
                ('os_dsc_problema', models.TextField(db_column='OS_DscProblema')),
                ('os_dth_abertura', models.DateTimeField(db_column='OS_DthAbertura')),
                ('os_fstatus', models.CharField(db_column='OS_FStatus', max_length=10)),
                ('os_nr_os_geradora', models.CharField(blank=True, db_column='OS_NrOSGeradora', max_length=20, null=True)),
                ('os_tempo_estimado', models.FloatField(blank=True, db_column='OS_TempoEstimado', null=True)),
                ('os_id_area_operacao', models.IntegerField(blank=True, db_column='OS_IdAreaOperacao', null=True)),
                ('are_cod_area_operacao', models.CharField(blank=True, db_column='ARE_CodAreaOperacao', max_length=20, null=True)),
                ('os_id_tipo_os', models.IntegerField(blank=True, db_column='OS_IdTipoOS', null=True)),
                ('tos_cod_tipo_os', models.CharField(blank=True, db_column='TOS_CodTipoOS', max_length=20, null=True)),
                ('os_dth_previsao_atendimento', models.DateTimeField(blank=True, db_column='OS_DthPrevisaoAtendimento', null=True)),
                ('os_contato_cliente', models.CharField(blank=True, db_column='OS_ContatoCliente', max_length=100, null=True)),
                ('os_contato_telefone', models.CharField(blank=True, db_column='OS_ContatoTelefone', max_length=20, null=True)),
                ('cli_id_empresa', models.IntegerField(db_column='CLI_IdEmpresa')),
                ('cli_nome', models.CharField(db_column='CLI_Nome', max_length=600)),
                ('cli_codigo_cliente', models.CharField(blank=True, db_column='CLI_CodigoCliente', max_length=20, null=True)),
                ('cli_cnpj_cpf', models.CharField(db_column='CLI_CNPJ_CPF', max_length=20)),
                ('dth_registro', models.DateTimeField(db_column='dthRegistro')),
            ],
            options={
                'db_table': 'cd_matra_ordens_servico',
                'ordering': ['os_dth_abertura'],
            },
        ),
    ]
