# Generated by Django 5.1.7 on 2025-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_acessorios_veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoriosveiculo',
            name='descricao',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
