# Generated by Django 5.1.7 on 2025-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_acessorios_veiculo', '0002_alter_acessoriosveiculo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoriosveiculo',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
