# Generated by Django 5.1.7 on 2025-03-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('ose_id_osocr', models.FloatField(db_column='OSE_IdOSOCr', primary_key=True, serialize=False)),
                ('ose_id_os', models.FloatField(db_column='OSE_IdOS')),
                ('ose_id_ocorrencia', models.FloatField(db_column='OSE_IdOcorrencia')),
                ('ose_dsc_ocorrencia', models.CharField(db_column='OSE_DscOcorrencia', max_length=100)),
                ('ose_id_usuario', models.FloatField(db_column='OSE_IdUsuario')),
                ('ose_dth_ocorrencia', models.DateTimeField(db_column='OSE_DthOcorrencia')),
                ('ose_observacao', models.TextField(blank=True, db_column='OSE_Observacao', null=True)),
                ('ose_latitude', models.FloatField(blank=True, db_column='OSE_Latitude', null=True)),
                ('ose_longitude', models.FloatField(blank=True, db_column='OSE_Longitude', null=True)),
                ('os_km', models.IntegerField(blank=True, db_column='OS_KM', null=True)),
                ('ose_id_agenda', models.FloatField(db_column='OSE_IdAgenda')),
                ('ose_id_situacao_ocorrencia', models.FloatField(blank=True, db_column='OSE_IdSituacaoOcorrencia', null=True)),
                ('ose_dsc_situacao_ocorrencia', models.CharField(db_column='OSE_DscSituacaoOcorrencia', max_length=50)),
                ('ose_id_tipo_origem', models.IntegerField(db_column='OSE_IdTipoOrigem')),
                ('ose_dth_original', models.DateTimeField(blank=True, db_column='OSE_DthOriginal', null=True)),
                ('ose_id_motivo_pausa', models.FloatField(blank=True, db_column='OSE_IdMotivoPausa', null=True)),
                ('ose_dsc_motivo_pausa', models.CharField(blank=True, db_column='OSE_DscMotivoPausa', max_length=200, null=True)),
                ('trf_cod_integracao', models.CharField(blank=True, db_column='TRF_CodIntegracao', max_length=200, null=True)),
                ('trf_tempo_estimado', models.FloatField(blank=True, db_column='TRF_TempoEstimado', null=True)),
                ('trf_dsc_tarefa', models.CharField(blank=True, db_column='TRF_DscTarefa', max_length=200, null=True)),
                ('trf_preco_tarefa', models.FloatField(blank=True, db_column='TRF_PrecoTarefa', null=True)),
                ('trf_quantidade', models.FloatField(blank=True, db_column='TRF_Quantidade', null=True)),
                ('trf_status', models.CharField(blank=True, db_column='TRF_Status', max_length=20, null=True)),
                ('usr_nome_usuario', models.CharField(db_column='USR_NomeUsuario', max_length=200)),
                ('usr_cod_usuario', models.CharField(db_column='USR_CodUsuario', max_length=20)),
                ('emp_cod_filial', models.CharField(db_column='EMP_CodFilial', max_length=10)),
                ('dth_registro', models.DateTimeField(db_column='dthRegistro')),
                ('os_nr_os', models.ForeignKey(db_column='OS_NrOS', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico_ocorrencia', to='ordens_servico.ordemservico')),
            ],
            options={
                'db_table': 'cd_matra_ocorrencias',
                'ordering': ['ose_dth_original'],
            },
        ),
    ]
