# Generated by Django 5.1.7 on 2025-03-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_culturas', '0001_initial'),
        ('crm_regioes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área em Hectares')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Data Ultima Edição')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_culturas.culturas', verbose_name='Cidade')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_regioes.regioes', verbose_name='Região')),
            ],
            options={
                'db_table': 'crm_areas_cultura',
                'ordering': ['regiao'],
            },
        ),
    ]
