# Generated by Django 5.1.7 on 2025-03-22 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_areas_cultura', '0002_areascultura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areascultura',
            name='ano',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2025)], verbose_name='Ano'),
        ),
    ]
