# Generated by Django 5.1.7 on 2025-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_areas_cultura', '0003_alter_areascultura_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areascultura',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='areascultura',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='areascultura',
            name='data_ultima_edicao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição'),
        ),
        migrations.AlterField(
            model_name='areascultura',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
