# Generated by Django 5.1.7 on 2025-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('usr_cod_usuario', models.CharField(db_column='USR_CodUsuario', max_length=30, primary_key=True, serialize=False)),
                ('usr_id_usuario', models.IntegerField(db_column='USR_IdUsuario')),
                ('usr_cpf', models.CharField(db_column='USR_CPF', max_length=14)),
                ('usr_nome_usuario', models.CharField(db_column='USR_NomeUsuario', max_length=200)),
                ('usr_login', models.CharField(db_column='USR_Login', max_length=200)),
                ('usr_tipo_usuario', models.CharField(db_column='USR_TipoUsuario', max_length=1)),
                ('usr_dsc_tipo_usuario', models.CharField(db_column='USR_DscTipoUsuario', max_length=20)),
                ('usr_id_empresa', models.IntegerField(db_column='USR_IdEmpresa')),
                ('usr_email', models.EmailField(blank=True, db_column='USR_Email', max_length=255, null=True)),
                ('usr_id_licenca', models.CharField(blank=True, db_column='USR_IdLicenca', max_length=50, null=True)),
                ('usr_dth_registro', models.DateTimeField(db_column='USR_DthRegistro')),
                ('emp_id_empresa', models.IntegerField(db_column='EMP_IdEmpresa')),
                ('emp_nome', models.CharField(db_column='EMP_Nome', max_length=200)),
                ('emp_cidade', models.CharField(db_column='EMP_Cidade', max_length=100)),
                ('emp_cod_filial', models.CharField(db_column='EMP_CodFilial', max_length=10)),
                ('dth_registro', models.DateTimeField(db_column='dthRegistro')),
            ],
            options={
                'db_table': 'cd_matra_tecnicos',
                'ordering': ['usr_nome_usuario'],
            },
        ),
    ]
