# Generated by Django 5.1.7 on 2025-03-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis_cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('tipo_empresa', models.CharField(max_length=30, verbose_name='Tipo da Empresa')),
                ('status', models.BooleanField(default=True, verbose_name='Status da Empresa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Data da Ultima Edição')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_cidades.cidades', verbose_name='Cidade da Empresa')),
            ],
            options={
                'db_table': 'crm_empresas',
                'ordering': ['nome'],
            },
        ),
    ]
