# Generated by Django 5.1.7 on 2025-03-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_produtos', '0001_initial'),
        ('crm_tipos_meta', '0001_initial'),
        ('crm_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meta de Vendas')),
                ('status', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_produtos.produtos')),
                ('tipo_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_tipos_meta.tiposmeta')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_vendedores.vendedores')),
            ],
            options={
                'db_table': 'crm_metas',
                'ordering': ['tipo_meta'],
            },
        ),
    ]
