# Generated by Django 5.1.7 on 2025-03-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_regioes', '0002_regioes_status'),
        ('sis_cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadesRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_cidades.cidades', verbose_name='Cidade do Cliente')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_regioes.regioes', verbose_name='Cidade do Cliente')),
            ],
            options={
                'db_table': 'crm_cidades_regiao',
                'ordering': ['regiao'],
            },
        ),
    ]
