# Generated by Django 5.1.7 on 2025-03-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cidades_regiao', '0001_initial'),
        ('crm_regioes', '0002_regioes_status'),
        ('sis_cidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadesregiao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_cidades.cidades', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cidadesregiao',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_regioes.regioes', verbose_name='Região da Cidade'),
        ),
    ]
