# Generated by Django 5.1.7 on 2025-03-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('age_id_agenda', models.IntegerField(db_column='AGE_IdAgenda', primary_key=True, serialize=False)),
                ('emp_cod_filial', models.CharField(db_column='EMP_CodFilial', max_length=10)),
                ('emp_id_empresa', models.IntegerField(db_column='EMP_IdEmpresa')),
                ('os_id_os', models.IntegerField(db_column='OS_IdOS')),
                ('os_fstatus', models.CharField(db_column='OS_FStatus', max_length=9)),
                ('os_id_cliente', models.IntegerField(db_column='OS_IdCliente')),
                ('cli_codigo_cliente', models.CharField(blank=True, db_column='CLI_CodigoCliente', max_length=20, null=True)),
                ('cli_nome', models.CharField(db_column='CLI_Nome', max_length=600)),
                ('cli_cnpj_cpf', models.CharField(db_column='CLI_CNPJ_CPF', max_length=18)),
                ('atd_id_atendimento', models.IntegerField(db_column='ATD_IdAtendimento')),
                ('usr_id_usuario', models.IntegerField(db_column='USR_IdUsuario')),
                ('usr_cod_usuario', models.CharField(db_column='USR_CodUsuario', max_length=20)),
                ('usr_nome_usuario', models.CharField(db_column='USR_NomeUsuario', max_length=200)),
                ('age_fstatus', models.CharField(db_column='AGE_FStatus', max_length=12)),
                ('age_dth_previsao_inicio', models.DateTimeField(db_column='AGE_DthPrevisaoInicio')),
                ('age_dth_previsao_fim', models.DateTimeField(db_column='AGE_DthPrevisaoFim')),
                ('tps_cod_servico_deslocamento', models.CharField(blank=True, db_column='TPS_CodServicoDeslocamento', max_length=50, null=True)),
                ('tps_dsc_tipo_servico_deslocamento', models.CharField(blank=True, db_column='TPS_DscTipoServicoDeslocamento', max_length=1000, null=True)),
                ('tps_cod_servico_atendimento', models.CharField(blank=True, db_column='TPS_CodServicoAtendimento', max_length=50, null=True)),
                ('tps_dsc_tipo_servico_atendimento', models.CharField(blank=True, db_column='TPS_DscTipoServicoAtendimento', max_length=1000, null=True)),
                ('dth_registro', models.DateTimeField(db_column='dthRegistro')),
                ('os_nr_os', models.ForeignKey(db_column='OS_NrOS', on_delete=django.db.models.deletion.CASCADE, to='ordens_servico.ordemservico')),
            ],
            options={
                'db_table': 'cd_matra_agendas',
                'ordering': ['age_dth_previsao_inicio'],
            },
        ),
    ]
