# Generated by Django 5.1.7 on 2025-03-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_familias_produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Modelo')),
                ('top_cat', models.CharField(max_length=10, verbose_name='Top Cat do Modelo')),
                ('custo_medio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Médio do Modelo')),
                ('venda_media', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venda Média do Modelo')),
                ('status', models.BooleanField(default=True, verbose_name='Status do Modelo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Data da Ultima Edição')),
                ('familia_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_familias_produto.familiasproduto', verbose_name='Familia do Produto do Modelo')),
            ],
            options={
                'db_table': 'crm_modelos',
                'ordering': ['descricao'],
            },
        ),
    ]
