# Generated by Django 5.1.7 on 2025-03-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_familias_produto', '0001_initial'),
        ('crm_modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='sigla',
            field=models.CharField(max_length=10, null=True, verbose_name='Sigla do Modelo'),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='familia_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_familias_produto.familiasproduto', verbose_name='Modelo do Modeloe'),
        ),
    ]
