# Generated by Django 5.1.7 on 2025-03-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_familias_produto', '0001_initial'),
        ('crm_marcas', '0001_initial'),
        ('crm_modelos', '0002_modelos_sigla_alter_modelos_familia_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='cor',
            field=models.CharField(max_length=20, null=True, verbose_name='Cor do Modelo'),
        ),
        migrations.AddField(
            model_name='modelos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_marcas.marcas', verbose_name='Marca do Modelo'),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='familia_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_familias_produto.familiasproduto', verbose_name='Familia do Produto do Modelo'),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='top_cat',
            field=models.CharField(max_length=10, null=True, verbose_name='Top Cat do Modelo'),
        ),
    ]
