# Generated by Django 5.1.7 on 2025-03-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_modelos', '0003_modelos_cor_modelos_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='top_cat',
        ),
    ]
