# Generated by Django 5.1.7 on 2025-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Tipo de Equipamento')),
                ('sigla', models.CharField(max_length=15, verbose_name='Sigla do Tipo de Equipamento')),
                ('status', models.BooleanField(default=True, verbose_name='Status do Tipo de Equipamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição')),
            ],
            options={
                'db_table': 'crm_produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
