# Generated by Django 5.1.7 on 2025-03-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Modelo')),
                ('sigla', models.CharField(max_length=10, null=True, verbose_name='Sigla do Modelo')),
                ('status', models.BooleanField(default=True, verbose_name='Status do Modelo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Criação')),
                ('data_ultima_edicao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Ultima Edição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_produtos.produtos', verbose_name='Tipo do Equipamento do Modelo')),
            ],
            options={
                'db_table': 'crm_familias_produto',
                'ordering': ['descricao'],
            },
        ),
    ]
