# Generated by Django 5.1.7 on 2025-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemposTecnico',
            fields=[
                ('tmp_id', models.CharField(db_column='TMP_Id', max_length=30, primary_key=True, serialize=False)),
                ('emp_cod_empresa', models.CharField(blank=True, db_column='EMP_CodEmpresa', max_length=10, null=True)),
                ('emp_cod_filial', models.CharField(blank=True, db_column='EMP_CodFilial', max_length=10, null=True)),
                ('usr_nome_usuario', models.CharField(blank=True, db_column='USR_NomeUsuario', max_length=200, null=True)),
                ('usr_cod_usuario', models.CharField(blank=True, db_column='USR_CodUsuario', max_length=20, null=True)),
                ('usr_id_usuario', models.IntegerField(db_column='USR_IdUsuario')),
                ('usr_ativo', models.IntegerField(db_column='USR_Ativo')),
                ('usr_cod_area_operacao', models.CharField(blank=True, db_column='USR_CodAreaOperacao', max_length=10, null=True)),
                ('tmp_ano', models.IntegerField(db_column='TMP_Ano')),
                ('tmp_mes', models.IntegerField(db_column='TMP_Mes')),
                ('tmp_minutos_disponivel', models.FloatField(db_column='TMP_MinutosDisponivel')),
                ('dth_registro', models.DateTimeField(db_column='dthRegistro')),
            ],
            options={
                'db_table': 'cd_matra_tempos_tecnico',
                'ordering': ['tmp_id'],
            },
        ),
    ]
